### ISSUE TITLE
Maybe you could update the code for python 3.x

### ISSUE THREAD

**Issue by zjplab** [pbharrin/machinelearninginaction#12]

**Comment by pbharrin** [comment]
I think this is a good idea, I have even had a professor contact me and tell me that if the code was updated to Python 3.X she would use the book for her class.  I am extremely busy, but maybe we could do this update as a community.

**Comment by pbharrin** [comment]
There now is a version for Python 3.X.  It doesn't work yet, but it is a place for us to work together.  
https://github.com/pbharrin/machinelearninginaction3x
